package com.kandemirmert.bookstore.enums;

public enum BookCategoriesEnum {

    ARTS_PHOTOGRAPHY,
    BIOGRAPHIES_MEMOIRS,
    BUSINESS_MONEY,
    CALENDARS,
    CHRISTIAN_BOOKS_BIBLES,
    COMICS_GRAPHIC_NOVELS,
    COMPUTERS_TECHNOLOGY,
    COOKBOOKS,
    FOOD_WINE,
    CRAFTS,
    HOBBIES_HOME,
    EDUCATION_TEACHING,
    ENGINEERING_TRANSPORTATION,
    HEALTH,
    FITNESS_DIETING,
    HISTORY,
    HUMOR_ENTERTAINMENT,
    LAW,
    LITERATURE_FICTION,
    MEDICAL_BOOKS,
    MYSTERY_THRILLER_SUSPENSE,
    PARENTING_RELATIONSHIPS,
    POLITICS_SOCIAL_SCIENCES,
    REFERENCE,
    RELIGION_SPIRITUALITY,
    ROMANCE,
    SCIENCE_MATH,
    SCIENCE_FICTION_FANTASY,
    SELF_HELP,
    SPORTS_OUTDOORS,
    TEST_PREPARATION,
    TRAVEL


}
